### ISSUE TITLE
Add the ability to retrieve the phone number/email/...

### ISSUE THREAD

**Issue by Shusshu** [lolobosse/ContactsAutoCompleteTextView#3]
Add the ability to retrieve the phone number/email/... from the selected person.

To be able to display the name of the selected person but use his email/phone/... for the rest of the app

**Comment by lolobosse** [comment]
I do not really get what you want to do: does the `getTextPattern` xml attribute does the trick?

**Comment by Shusshu** [comment]
But this returns the data directly into the AutoCompleteTextView.
What if I want to display the Name is the AutoCompleteTextView and also get the phone number like this:

```
AutoCompleteTextView  myAutoCompleteTextView ...
myAutoCompleteTextView.getPhone()
```

or 

```
myAutoCompleteTextView.getContact()
```

**Comment by manuelsilverio** [comment]
hey guys, What Wushu wants to do is to be able to retrieve a string of the name or number, so that would be adding another public method different than gettext.

public String getName(){
   if(isSomeoneSelected()) {return selected.getName().toString();}
   else{return null}  
}

**Comment by lolobosse** [comment]
Ok, implemented it as @manuelsilverio01 proposed.

Can you test it? It is not released yet, you have to compile the sources

**Comment by Shusshu** [comment]
Perfect
