### ISSUE TITLE
Mix type of data

### ISSUE THREAD

**Issue by Shusshu** [lolobosse/ContactsAutoCompleteTextView#4]
Would it be possible to mix the type of data ?

For example:

auto:typeOfData="phone|email" would autocomplete contacts with a phone or/and an email

**Comment by lolobosse** [comment]
Good idea, I'll try to manage that today.

**Comment by Shusshu** [comment]
Nice

**Comment by lolobosse** [comment]
Ok, I tried it but it is not so easy because the structure of the class is not perfect to do such a feature, I need to rethink a bit the workflow, it could last a bit more than expected.

**Comment by lolobosse** [comment]
Can you test it ?

**Comment by Shusshu** [comment]
Yes it works.
