### ISSUE TITLE
Able to retrieve the data of the contact after it has been selected by the listener

### ISSUE THREAD

**Issue by Shusshu** [lolobosse/ContactsAutoCompleteTextView#6]
Either add a new listener we can use to catch that data once it is set

Or maybe you can just switch 2 lines:

```
this.setOnItemClickListener(new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            setText(((People) AutoCompleteContactTextView.this.getAdapter().getItem(position)).getName().toString());
            selected = (People) getAdapter().getItem(position);
        }
    });
```

You should put `selected = ...` in front of `setText`

https://github.com/lolobosse/ContactsAutoCompleteTextView/blob/master/contactsautocompletetextview/src/main/java/com/meyerlaurent/cactv/AutoCompleteContactTextView.java#L115

I would prefer the listener so I don't need to listen to every Text change with the TextWatcher

**Comment by lolobosse** [comment]
Good one, I'll try to make it today and do a release until the end of the week :+1:

**Comment by Shusshu** [comment]
Thx

**Comment by lolobosse** [comment]
Can you say me if you're satisfied?

**Comment by Shusshu** [comment]
That would work but it's not the best solution.

Thx
